par(mfrow=c(2,2))
plot(newdata1$Datetime, newdata1$Global_active_power,type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
plot(newdata1$Datetime, newdata1$Voltage,type ="l",xlab = "datetime", ylab = "Voltage")
plot(newdata1$Datetime, newdata1$Sub_metering_1, col="black", type="l",xlab = "", ylab = "Energy sub metering")
points(newdata1$Datetime, newdata1$Sub_metering_2, type="l", pch=22, lty=2, col="red",xlab = "", ylab = "Energy sub metering")
points(newdata1$Datetime, newdata1$Sub_metering_3, type="l", pch=22, lty=2, col="blue", xlab = "", ylab = "Energy sub metering")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))                                                                        "Sub_metering_2", "Sub_metering_3"))
plot(newdata1$Datetime, newdata1$Global_reactive_power, type ="l",xlab = "datetime", ylab = "Global_reactive_power")
png("plot4.png", width=480, height=480)
dev.off()